apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-gh-env-template
  title: Test GH Env Template
  description: Create a test GH Env
  tags:
    - react
    - cra
spec:
  owner: soapraj@gmail.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Environment Inputs
      required:
        - environment_name
      properties:
        environment_name:
          title: Description
          type: string
          description: Name of the environment
        wait_timer:
          title: Description
          type: integer
          description: Number between 0 and 43,200 (30 days)
        prevent_self_review:
          title: Prevent Self Review
          type: boolean
          description: Whether or not a user who created the job is prevented from approving their own job.
        reviewers:
          title: Reviewers
          type: string
          description: The people or teams that may review jobs that reference the environment. Add up to six users or teams as reviewers that have at least read access to the repository.
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: "public"

    - id: environment
      name: Environment
      action: github:environment:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        name: ${{ parameters.environment_name }}
        wait_timer: ${{ parameters.wait_timer }}
        prevent_self_review: ${{ parameters.prevent_self_review }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
